services:
  db:
    image: postgres:16                   # imagen que se utilizará para crear el contenedor
    container_name: casaesperanza-db
    environment:
      POSTGRES_DB: casaesperanza         # Nombre de la base de datos
      POSTGRES_USER: BDcasa
      POSTGRES_PASSWORD: BDcasa
    ports:
      - "5432:5432"                      # HOST:CONTENEDOR
    volumes:
      - pgdata:/var/lib/postgresql/data  # Carpeta dentro del contenedor donde se persisten los datos al volumen pgdata

volumes:
  pgdata:
