package es.uma.tfg.casaesperanza.entity.enums;

/**
 * RF2.2 Asignación de funciones específicas
 * <p>
 * Funciones basadas en Tabla resumen de roles y permisos, sección 4.3.6 del DGR.
 */
public enum Capacidad {
    AGENDAR_SERVICIOS,
    CONCEDER_HABILITACION_TEMPORAL,
    CONSULTAR_LOG_AUDITORIA,
    CONSULTAR_NOTAS_AMIGO,
    CREAR_ASIENTOS,
    CREAR_NOTA_PRIVADA,
    ENTREGAR_ROPA,
    ESCALAR_NIVEL_3,
    EXPORTAR_INFORMES,
    GESTIONAR_ARMARIO,
    GESTIONAR_CUENTAS_USUARIO,
    IMPORTAR_DATOS,
    IMPORTAR_EXTRACTOS,
    OPERAR_LAVANDERIA,
    REGISTRAR_ENTREGA_ALIMENTARIA,
    REGISTRAR_GASTO_AMIGO,
    REGISTRAR_SALIDA_ALIMENTARIA,
    REGISTRAR_AMIGO
}
